#include "if_adc.h"

//! External handles generated by CubeMX
extern ADC_HandleTypeDef hadc1;
extern DMA_HandleTypeDef hdma_adc1;

//! DMA buffer to hold ADC values
static volatile uint16_t adc_buffer[ADC_NUM_CHANNELS];

void if_adc_init(void) {
    //! Initialize the ADC peripheral
    HAL_ADCEx_Calibration_Start(&hadc1);

    //! Start ADC in DMA mode
    HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_buffer, ADC_NUM_CHANNELS);
}

uint16_t if_adc_get_raw_value(adc_channel_e channel) {
    if (channel < ADC_NUM_CHANNELS) {
        //! Return the latest ADC value from the DMA buffer
        return (uint16_t)adc_buffer[channel];
    }
    return 0;
}
